# Generated by Django 5.0.7 on 2024-08-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transition',
            field=models.ManyToManyField(to='transition.transfermodel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=1000),
        ),
    ]
