# Generated by Django 5.0.7 on 2024-08-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0002_userprofile_transition_alter_userprofile_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
    ]
