# Generated by Django 5.0.7 on 2024-08-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0004_alter_transfermodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfermodel',
            name='read_status_recipient',
        ),
        migrations.RemoveField(
            model_name='transfermodel',
            name='read_status_sender',
        ),
    ]
