# Generated by Django 5.0.7 on 2024-08-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0006_transfermodel_read_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfermodel',
            name='read_status',
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='read_status_recipient',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='read_status_sender',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
