# Generated by Django 5.0.7 on 2024-08-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0007_remove_transfermodel_read_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transition',
            field=models.ManyToManyField(blank=True, null=True, to='transition.transfermodel'),
        ),
    ]
