# Generated by Django 5.0.7 on 2024-08-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0008_userprofile_avatar_alter_userprofile_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='transition',
            field=models.ManyToManyField(to='transition.transfermodel'),
        ),
    ]
